In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open('words.txt', 'r').read().splitlines()
words[:8]

['abakus',
 'abandon',
 'abazja',
 'abażur',
 'abażurek',
 'abdukcja',
 'abduktor',
 'abdykacja']

In [3]:
len(words)

48178

In [5]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'r', 18: 's', 19: 't', 20: 'u', 21: 'v', 22: 'w', 23: 'y', 24: 'z', 25: 'ó', 26: 'ą', 27: 'ć', 28: 'ę', 29: 'ł', 30: 'ń', 31: 'ś', 32: 'ź', 33: 'ż', 0: '.'}


In [7]:
# dataset

block_size = 3  # context size
X, Y = [], []

for w in words[:5]:
    print(w)
    context = [0] * block_size

    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '---->', itos[ix])
        context = context[1:] + [ix]  # crop and append

X = torch.tensor(X)
Y = torch.tensor(Y)

abakus
... ----> a
..a ----> b
.ab ----> a
aba ----> k
bak ----> u
aku ----> s
kus ----> .
abandon
... ----> a
..a ----> b
.ab ----> a
aba ----> n
ban ----> d
and ----> o
ndo ----> n
don ----> .
abazja
... ----> a
..a ----> b
.ab ----> a
aba ----> z
baz ----> j
azj ----> a
zja ----> .
abażur
... ----> a
..a ----> b
.ab ----> a
aba ----> ż
baż ----> u
ażu ----> r
żur ----> .
abażurek
... ----> a
..a ----> b
.ab ----> a
aba ----> ż
baż ----> u
ażu ----> r
żur ----> e
ure ----> k
rek ----> .


In [12]:
C = torch.randn((34, 2))

In [13]:
C

tensor([[-1.2543, -0.4064],
        [-1.0981,  1.9069],
        [ 0.2806, -0.4336],
        [ 0.9208, -1.1763],
        [ 0.9091,  0.7917],
        [ 1.3909,  1.2563],
        [ 0.2430, -0.9940],
        [-1.2703, -0.3331],
        [ 0.5769, -0.1403],
        [ 0.6624, -0.3708],
        [ 0.1239,  0.2619],
        [ 0.0276, -1.5064],
        [-0.7156, -0.1811],
        [-1.8532,  0.9671],
        [ 0.1667, -0.3658],
        [ 0.6337, -0.4637],
        [-0.8155,  0.8259],
        [ 0.1423,  1.4403],
        [ 0.8536,  0.3064],
        [ 0.7875,  0.1714],
        [-1.5536,  1.1965],
        [-0.7198, -0.2246],
        [ 0.1329, -1.6392],
        [-0.7724, -0.1415],
        [-0.2690,  1.1917],
        [ 0.4139, -1.2536],
        [-0.1777,  0.4885],
        [ 0.5043, -0.2197],
        [-1.7749,  1.4796],
        [ 1.3764,  0.7525],
        [ 1.2112, -0.4106],
        [-0.8240,  0.1509],
        [-0.5455, -1.3891],
        [-0.6212,  1.2181]])

In [14]:
F.one_hot(torch.tensor(5), num_classes=34)

tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
F.one_hot(torch.tensor(5), num_classes=34).float() @ C

tensor([1.3909, 1.2563])